### ISSUE TITLE
DeleteAuxFilesMacros.plist question

### ISSUE THREAD

**Issue by causalcat** [herbs/herbs.github.io#2]
Hi,

I have used the deleteauxfiles macro to delete the auxiliary files in TexShop. It works perfectly for the files with the exact same name as the .tex file. However, I do not know how to modify the macro so that can delete files that are created from this .tex but have slightly different name. Examples of such files are those generated when I use the latexmk, pdflatexmk or xelatexmk.

There is some comment in the macro stating 
"-- If your file is document.tex, setting this true will delete only document.aux, document.log, etc., but NOT otherdoc.aux, otherdoc.log, etc."
but it is not clear to me which value to set true/false to manage to delete these files. 

Could you please help me with this?

Thanks in advance!

Thanks in advance.

**Comment by herbs** [comment]
> On Jun 23, 2024, at 5:32 AM, causalcat ***@***.***> wrote:
> 
> 
> Hi,
> I have used the deleteauxfiles macro to delete the auxiliary files in TexShop. It works perfectly for the files with the exact same name as the .tex file. However, I do not know how to modify the macro so that can delete files that are created from this .tex but have slightly different name. Examples of such files are those generated when I use the latexmk, pdflatexmk or xelatexmk.
> There is some comment in the macro stating
> "-- If your file is document.tex, setting this true will delete only document.aux, document.log, etc., but NOT otherdoc.aux, otherdoc.log, etc."
> but it is not clear to me which value to set true/false to manage to delete these files.
> Could you please help me with this?
> Thanks in advance!
> Thanks in advance.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Howdy,

I've spent some time trying to do this and have failed!

I'm afraid that can't be done with that macro. There are many variations of that sort of thing that would be nice for a particular case (e.g., one very simple case is when you divide a document into a master and separate chapters) but each case would be different.

Good Luck,

Herb Schulz
***@***.***

**Comment by causalcat** [comment]
Okay, thanks a lot for your time :-)
